version: 2
jobs:
    python27:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - checkout
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                conda config --add channels conda-forge
                conda update conda conda-build
                mkdir packages
                conda-build conda --python=27 --output-folder packages
                EOF
            - persist_to_workspace:
                root: .
                paths: packages/*

    python36:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - checkout
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                conda config --add channels conda-forge
                conda update conda conda-build
                mkdir packages
                conda-build conda --python=36 --output-folder packages
                EOF
            - persist_to_workspace:
                root: .
                paths: packages/*

    deploy:
        steps:
            - attach_workspace:
                at: /packages
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                anaconda upload --token $ANACONDA_TOKEN --user $ANACONDA_USER /packages/*
                EOF

workflows:
    version: 2
    build_and_test:
        jobs:
            - python27
            - python36
            - deploy:
                requires:
                    - python27
                    - python36
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/

