version: 2
jobs:
    python27:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - checkout
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                conda config --add channels conda-forge
                conda update conda conda-build
                mkdir packages
                conda-build conda --python=27
                cp $(/opt/docker/bin/entrypoint /bin/bash -c 'conda-build conda --python=27 --output') packages
                EOF
            - persist_to_workspace:
                root: .
                paths: packages/*

    python36:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - checkout
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                conda config --add channels conda-forge
                conda update conda conda-build
                mkdir packages
                conda-build conda --python=36
                cp $(/opt/docker/bin/entrypoint /bin/bash -c 'conda-build conda --python=36 --output') packages
                EOF
            - persist_to_workspace:
                root: .
                paths: packages/*

    conda_upload:
        working_directory: /conda-build
        docker:
            - image: condaforge/linux-anvil
        steps:
            - attach_workspace:
                at: /workspace
            - run: |
                /opt/docker/bin/entrypoint /bin/bash << EOF
                anaconda -t \$ANACONDA_TOKEN upload --user \$ANACONDA_USER /workspace/packages/*
                EOF

workflows:
    version: 2
    conda_build_and_upload:
        jobs:
            - python27
            - python36
            - conda_upload:
                requires:
                    - python27
                    - python36
                filters:
                    tags:
                        only: /.*/
                    branches:
                        only: /.*/

