package:
    name: umtools
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    entry_points:
        - slabancil = umtools.slabancil:main
        - iris2netcdf = umtools.iris2netcdf:main

requirements:
    build:
        - python
        - pip
        - pbr
    run:
        - python
        - six
        - iris

test:
    source_files:
        - setup.cfg
        - conftest.py
        - test
    requires:
        - pytest
    commands:
        - py.test

about:
    home: https://github.com/coecms/umtools
    license: Apache 2.0
    license_file: LICENSE-2.0.txt
    summary: umtools
